### ISSUE TITLE
OTP EA on market.link

### ISSUE THREAD

**Issue by PatrickAlphaC** [Machu-Pichu/hackathon#3]
Hey team! Wanted to congratulate you for submitting this project! It's very nice. I was wondering if you had a chance to upload your external adapter to market.link, you could show off your stuff and help other engineers with this awesome tool!

**Comment by kvutien** [comment]
Thank you for your kind words, Patrick. The whole team is now busy catching up with our lessons in the ConsenSys BootCamp. We left it a bit idle during the hackathon :-)
I'll check with them.

**Comment by kuldeep23907** [comment]
Hi @PatrickAlphaC 

Could you please share any doc/steps following which we can upload OTP EA in Chainlink Market - Kovan?

Thanks

**Comment by PatrickAlphaC** [comment]
https://market.link/auth/signin < Create an account and sign in, then just add a `.yml` file into your repo and upload:

https://docs.linkpool.io/docs/market_adapter_listing

**Comment by kuldeep23907** [comment]
Great! Thanks

**Comment by kuldeep23907** [comment]
@PatrickAlphaC done! Please confirm if it's there now.

repo: https://github.com/kuldeep23907/OTP-External-Adapter

adapter name: One_Time_Password_EA

**Comment by PatrickAlphaC** [comment]
Almost! You should be able to upload it to https://market.link/search/adapters << If you sign in you can go to your account and add and adapter. 

Looks like you got the .yml file up though!

**Comment by kuldeep23907** [comment]
@PatrickAlphaC I am getting this error.

Validation error

- Adapter node identifier needs to only contain letters, numbers and spces

But value seems to be a valid value.

**Comment by kuldeep23907** [comment]
Never mind. Got it working! Thanks

**Comment by PatrickAlphaC** [comment]
Awesome! Nice work!!

**Comment by PatrickAlphaC** [comment]
https://market.link/adapters/afa0e057-8197-407b-b6ef-7cf1caf77022
